# numpy arrays

In [1]:
import numpy as np

In [2]:
a = [3,4,5]
a

[3, 4, 5]

In [3]:
np.array(a)

array([3, 4, 5])

In [4]:
b=[[2,3,4],[6,3,3],[3,5,6]]
np.array(b)

array([[2, 3, 4],
       [6, 3, 3],
       [3, 5, 6]])

In [5]:
b

[[2, 3, 4], [6, 3, 3], [3, 5, 6]]

arange

In [7]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
arr=np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [13]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones((7,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.linspace(0,100,9)

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

In [24]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

random

In [26]:
# gives a random no between 0-1
np.random.rand(4)

array([0.10961479, 0.53564478, 0.15114561, 0.48554871])

In [27]:
np.random.rand(7,4)

array([[0.63433685, 0.86133018, 0.68576197, 0.84254083],
       [0.89349671, 0.38220973, 0.40684061, 0.26722552],
       [0.84525783, 0.02233828, 0.75589913, 0.75414866],
       [0.56923574, 0.66367821, 0.50375169, 0.72130046],
       [0.19075068, 0.18472889, 0.09626267, 0.55627353],
       [0.51078692, 0.65705095, 0.62940399, 0.19642393],
       [0.61032222, 0.70174151, 0.7902092 , 0.3403302 ]])

In [29]:
# gives a random no between all negative to 1
np.random.randn(6)

array([ 0.16627978,  0.67854533,  0.63320445,  0.47401832, -0.04625647,
        1.38748155])

In [30]:
np.random.randn(4,4)

array([[ 0.39023831, -0.47818266, -1.36142317, -0.70471116],
       [ 0.39663957, -0.15904568,  1.03844065,  1.76162224],
       [-0.6353653 , -1.10463314, -1.65597956, -0.09541428],
       [-1.08663709, -1.19933064,  0.68022632, -0.78381853]])

In [40]:
#give you random no between 0 and infinity
np.random.randint(0,100,)


79

In [47]:
np.random.randint(0,999,7)


array([ 45, 157, 201, 533, 170, 625, 940])

array and attributes

In [49]:
arr = np.arange(0,40)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [51]:
arr.shape

(40,)

In [54]:
arr.reshape(5,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [56]:
q = np.random.randint(0,50,10)
q

array([39, 17, 13, 36,  0, 39, 19, 32, 41, 12])

In [57]:
np.max(q)

41

In [58]:
np.min(q)

0

In [60]:
q.reshape(5,2)

array([[39, 17],
       [13, 36],
       [ 0, 39],
       [19, 32],
       [41, 12]])

# indexing and slicing

In [70]:
ind = np.arange(0,80,3)
ind

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78])

In [71]:
ind[8]

24

In [73]:
ind[0:6]

array([ 0,  3,  6,  9, 12, 15])

In [74]:
ind[:7]

array([ 0,  3,  6,  9, 12, 15, 18])

In [76]:
ind[8:]

array([24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72,
       75, 78])

In [77]:
ind[:]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78])

In [80]:
ind[0:5]=100
ind

array([100, 100, 100, 100, 100,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78])

In [81]:
ind.max()

100

In [87]:
s = ind[0:5] =11
ind


array([11, 11, 11, 11, 11, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78])

In [88]:
ind.shape


(27,)

In [96]:
zz = ind.reshape(3,9)

In [97]:
zz

array([[11, 11, 11, 11, 11, 15, 18, 21, 24],
       [27, 30, 33, 36, 39, 42, 45, 48, 51],
       [54, 57, 60, 63, 66, 69, 72, 75, 78]])

In [98]:
zz[1][1]

30

In [101]:
zz[2,7]

75

In [105]:
zz[:2,5:]

array([[15, 18, 21, 24],
       [42, 45, 48, 51]])

In [107]:
zz[1:,:4]

array([[27, 30, 33, 36],
       [54, 57, 60, 63]])

In [110]:
fan = np.zeros((10,10))
fan

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [118]:
aa = fan.shape[1]
aa

10

In [119]:
for i in range(aa):
  fan[i]=i
fan


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [120]:
fan[[3,5,7,9]]

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [123]:
rr = np.arange(20)
rr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [124]:
rr[rr<7]

array([0, 1, 2, 3, 4, 5, 6])

In [125]:
d =7
rr[rr>d]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# Numpy operation

In [126]:
ggg = np.arange(0,100,5)
ggg

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [133]:
hhh = np.arange(0,200,10)
hhh

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190])

In [134]:
ggg + hhh

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135, 150, 165, 180,
       195, 210, 225, 240, 255, 270, 285])

In [129]:
hhh - ggg

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [130]:
ggg-hhh

array([  0,  -5, -10, -15, -20, -25, -30, -35, -40, -45, -50, -55, -60,
       -65, -70, -75, -80, -85, -90, -95])

In [135]:
hhh/ggg

<ipython-input-135-d975800c8fbb>:1: RuntimeWarning: invalid value encountered in divide
  hhh/ggg


array([nan,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [136]:
ggg*hhh

array([    0,    50,   200,   450,   800,  1250,  1800,  2450,  3200,
        4050,  5000,  6050,  7200,  8450,  9800, 11250, 12800, 14450,
       16200, 18050])

In [137]:
ggg**hhh

array([                   1,              9765625,  7766279631452241920,
       -9155667389781577439,                    0, -3842938066129721103,
        1152921504606846976, -7980554507852430823,                    0,
        6221149592075408201,                    0, -6921680713579778383,
                          0,  8074318994125631617,                    0,
        4980430518688881513,                    0,  2784293464491949849,
                          0, -2670577047901657919])

In [139]:
hhh/5

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28., 30., 32., 34., 36., 38.])

In [140]:
5/ggg

<ipython-input-140-442fc98fb237>:1: RuntimeWarning: divide by zero encountered in divide
  5/ggg


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [142]:
np.sqrt(hhh)

array([ 0.        ,  3.16227766,  4.47213595,  5.47722558,  6.32455532,
        7.07106781,  7.74596669,  8.36660027,  8.94427191,  9.48683298,
       10.        , 10.48808848, 10.95445115, 11.40175425, 11.83215957,
       12.24744871, 12.64911064, 13.03840481, 13.41640786, 13.78404875])

In [143]:
hhh**3

array([      0,    1000,    8000,   27000,   64000,  125000,  216000,
        343000,  512000,  729000, 1000000, 1331000, 1728000, 2197000,
       2744000, 3375000, 4096000, 4913000, 5832000, 6859000])